# Generated by Django 4.1.5 on 2023-01-27 01:13

import basicapp.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_remove_users_username_alter_users_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', basicapp.models.UserManager()),
            ],
        ),
    ]
