# Generated by Django 4.1.5 on 2023-01-28 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0003_alter_users_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='driver_acc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rides',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rides',
            name='ride_id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rides',
            name='sharable',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='rides',
            name='status',
            field=models.CharField(choices=[('op', 'open'), ('cf', 'confirmed'), ('cp', 'complete')], max_length=2, null=True),
        ),
    ]
