# Generated by Django 4.1.5 on 2023-01-30 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0006_alter_users_name'),
        ('basicapp', '0006_rides_required_vehic_type_alter_users_name'),
    ]

    operations = [
    ]
