# Generated by Django 4.1.5 on 2023-01-26 20:50

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_driver', models.BooleanField(default=False, null=True)),
                ('vehic_type', models.CharField(choices=[('su', 'suv'), ('mp', 'mpv'), ('sd', 'sedan')], max_length=2, null=True)),
                ('lice_plate_number', models.CharField(max_length=10, null=True)),
                ('max_pass_num', models.PositiveSmallIntegerField(null=True)),
                ('other_reg', models.TextField(max_length=300, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('ride_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dest_addr', models.CharField(max_length=200)),
                ('arr_date_time', models.DateTimeField()),
                ('party_num', models.PositiveSmallIntegerField()),
                ('sharable', models.BooleanField()),
                ('status', models.CharField(choices=[('op', 'open'), ('cf', 'confirmed'), ('cp', 'complete')], max_length=2)),
                ('other_reg', models.TextField(max_length=300, null=True)),
                ('driver_acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sharers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_party_num', models.PositiveSmallIntegerField()),
                ('share_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_ride', to='basicapp.rides')),
                ('sharer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sharers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
