# Generated by Django 4.1.5 on 2023-01-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0005_users_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='required_vehic_type',
            field=models.CharField(choices=[('su', 'suv'), ('mp', 'mpv'), ('sd', 'sedan'), ('al', 'alltypes')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
